### ISSUE TITLE
wrap yakchat module to allow embed as <script>

### ISSUE THREAD

**Issue by ReinsBrain** [rebelstackio/yakchat#20]
- [ ] has to be able to access DOM
- [ ] easy embed by locating script tag
- [ ] packaging with parcel

**Comment by jegj** [comment]
@ReinsBrain  @oreyes1991  **Blocked** The frontscript use metaflux as a dependecy - that will make the final script a bit bigger. I thought we going to use vanilla js to create this "plugin" , to  load faster components. Also i think we need to make two releases or final assets, one for the final script like `yakchat.min.js` and another one for the styles `yakchat.min.css` and those file should be included in the client's web pages as:
```html
<head>
     <link rel="stylesheet" href="https://rebelcdn.com/yakchat/x.y.z/yakchat.min.css">
     <script href="https://rebelcdn.com/yakchat/x.y.z/yakchat.min.js"></script>
</head>
<body>
</body>
```
but the styles are embededd in the sample html file with `style-loader` and `css-loader`. We have to remember that this script will be included as a plugin so this approach doesn't work( for development is ok), the css inclusion should be manually via tags or all the css should be inside the main script so webpack can packaging all the content. Right now is not possible to pack the css content  and the final assets has a size of **1.1MB** even minimized ( too big for an small plugin)

**Comment by ReinsBrain** [comment]
> but the styles are embededd in the sample html file with style-loader and css-loader. We have to remember that this script will be included as a plugin so this approach doesn't work( for development is ok), the css inclusion should be manually via tags or all the css should be inside the main script so webpack can packaging all the content. Right now is not possible to pack the css content and the final assets has a size of 1.1MB even minimized ( too big for an small plugin)

ok i will create a new ticket to solve that - parcel should be able to do a good job of wrapping it up - also minifying...
