### ISSUE TITLE
remove weight from style-loader and css-loader

### ISSUE THREAD

**Issue by ReinsBrain** [rebelstackio/yakchat#46]
- [ ] unblock https://github.com/rebelstackio/yakchat/issues/20

**Comment by oreyes1991** [comment]
with parceljs this can be archive, so i gonna remove webpack to close this issue.

**Comment by jegj** [comment]
@ReinsBrain  @pablolimo  How are we going to handle the fact that firebase is the bigger dependecy in the front-site script. With Parcel the assets still has a size of 1MB .... we need to figure out how to have a lightweight version of firebase or just import the required only
